### ISSUE TITLE
Transitions do not work with gutterWidth option, without specifying columnWidth

### ISSUE THREAD

**Issue by wahidrahim** [kristianmandrup/masonry-rails#17]
Scenario:
    `<div id='posts-container', class='transitions-enabled'> ... </div>`

In `application.scss` I have included `@import "masonry/transitions"`

If I initialize masonry with:

    $(function() {
        $('#posts-container').masonry({
            itemSelector: '.post',
            gutterWidth: 10
        });
    });

the transitions DO NOT work. However adding a value to columnWidth re-enables transitions... so if I do:

    $(function() {
        $('#posts-container').masonry({
            itemSelector: '.post',
            columnWidth: 1,
            gutterWidth: 10
        });
    });

the transitions work again, if I change it to 0, the transitions stop working.

**Comment by kristianmandrup** [comment]
You are welcome to make whatever fixes or refactoring for more flexibility etc and make a pull request ;)
I'm not really maintaining this project beyond that at this point...
