### ISSUE TITLE
images loaded under each other after images are loaded

### ISSUE THREAD

**Issue by TomSchillemans** [kristianmandrup/masonry-rails#18]
If I go to my home page where a bunch of images are they are loaded under each other instead of next to each other. However when I refresh the page after they are next to each other again.

I don't know what this could be. Masonry is working!

``` coffee
$ ->
  $('#pins').imagesLoaded ->
    $('#pins').masonry
      itemSelector: '.box'
      isFitWith: true
```

That is my coffescript file as it stands at the moment.

### EDIT
It looks like it only happens of the images are cached!
So I think it has something to do with the imagesLoaded thing.

**Comment by TomSchillemans** [comment]
Ok, I solved the issue. I made an document load method and pasted this code in there. Now it works!

**Comment by kristianmandrup** [comment]
Awesome!!

**Comment by expoo** [comment]
Same happened to me, my problem was that i forgot to add
 "//= require jquery.turbolinks" into my application.js folder.
