### ISSUE TITLE
Breaks when using Twitter Bootstrap

### ISSUE THREAD

**Issue by kristianmandrup** [kristianmandrup/masonry-rails#2]
When using Twitter Bootstrap, the masonry and isotope calculations seem to break down for some reason. If anyone has a solution to this, please let me know!!! :)

**Comment by Judahmeek** [comment]
This issue can likely be closed. A friend of mine was able to use this gem with Bootstrap (Rails 5) without problems: https://github.com/choonggg/flickr-search

**Comment by kristianmandrup** [comment]
Thanks :)

**Comment by Judahmeek** [comment]
What I should have said was that my friend used this gem in combination with Bootstrap without any complaints. Looking at the responsiveness of his [demo app on heroku],(https://flickr-searchy.herokuapp.com/search?utf8=%E2%9C%93&search_form%5Bsearch%5D=tofu&commit=Search) however, I suspect that there are further issues.
![image](https://cloud.githubusercontent.com/assets/8206741/15486144/228823fc-2109-11e6-9306-a1bc4944e87c.png)

**Comment by Judahmeek** [comment]
Also, the results from shrinking the browser width instantly through Chrome's "Restore Down" button differ from the results of shrinking width slowly by using the cursor/mouse to drag the edge of the browser over. Both results appear deterministic, however, and Chrome's web dev result can be seen while slowly shrinking the browser to around 700 px.
